### ISSUE TITLE
Understanding LDA Theory

### ISSUE THREAD

**Issue by ss3n** [shiladityasen/274B-Yelp#1]
Issues concerning theoretical understanding of how LDA works

**Comment by SyedAzizEnam** [comment]
High level understanding of LDA:
http://blog.echen.me/2011/08/22/introduction-to-latent-dirichlet-allocation/

**Comment by SyedAzizEnam** [comment]
Lecture on LDA:
http://videolectures.net/mlss09uk_blei_tm/

Implementation notes:
http://cseweb.ucsd.edu/~elkan/250B/topicmodels.pdf

**Comment by ss3n** [comment]
Thanks @SyedAzizEnam!

I have gone through the video lecture... Tomorrow let's come up with the partitioning of the module for LDA so that we both may be able to work on it?

One thing I was thinking is that if we can build our LDA library such that it can be robust enough to support any prior and not be restricted to Dirichlet distribution only. We will be needing this to implement the approach on the paper since it involves a modified prior.
