### ISSUE TITLE
Computing gradient functions

### ISSUE THREAD

**Issue by ss3n** [shiladityasen/274B-Yelp#5]
@SyedAzizEnam : I am writing down the variables for which we need to define the gradient functions in `HFT` ... We can keep picking them one by one and implement them. Before we start implementing the gradients however, we should merge our branches once the implementations of `log-likelihood` and `Gibbs sampler` have been incorporated in `ReviewModel`.  

The gradient functions to be implemented are:  
- `alpha` (`RatingModel`)
- `beta_user` (`RatingModel`)
- `beta_item` (`RatingModel`)
- `gamma_user` (`RatingModel`)
- `gamma_item` (`RatingModel`)
- `kappa` (`HFT`)
- `phi` (`HFT`)

**Comment by ss3n** [comment]
After we merge, we can create separate branches again till we finish implementing the gradients and merge back.  
I wish to pick `gamma_user` and `gamma_item` to start off.

**Comment by shiladityasen** [comment]
[](https://docs.google.com/drawings/d/19tTwx8Y454ibVSqU4E_qvCTe5sg5-FsRuSp-qp-30m0/pub?w=960&h=720)
